nickname = "lunchbot"
channels = ["#rust-spam"]
server = "54.85.60.193"
port = 6697
use_ssl = true
should_ghost = true
ghost_sequence = ["RECOVER"]
burst_window_length = 5
max_messages_in_burst = 4
encoding = "UTF-8"